// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ActionsMenu.vue')['default']
    Bag: typeof import('./src/components/Bag.vue')['default']
    CollectionEntries: typeof import('./src/components/CollectionEntries.vue')['default']
    CollectionEntry: typeof import('./src/components/CollectionEntry.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    FAB: typeof import('./src/components/FAB.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    IconDetail: typeof import('./src/components/IconDetail.vue')['default']
    Icons: typeof import('./src/components/Icons.vue')['default']
    IconSet: typeof import('./src/components/IconSet.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavElectron: typeof import('./src/components/electron/NavElectron.vue')['default']
    NavPlaceholder: typeof import('./src/components/electron/NavPlaceholder.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    SearchElectron: typeof import('./src/components/electron/SearchElectron.vue')['default']
    WithNavbar: typeof import('./src/components/WithNavbar.vue')['default']
  }
}

export { }
