/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./components/ActionsMenu.vue')['default']
    Bag: typeof import('./components/Bag.vue')['default']
    CollectionEntries: typeof import('./components/CollectionEntries.vue')['default']
    CollectionEntry: typeof import('./components/CollectionEntry.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    CustomSelect: typeof import('./components/CustomSelect.vue')['default']
    DarkSwitcher: typeof import('./components/DarkSwitcher.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    FAB: typeof import('./components/FAB.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelpPage: typeof import('./components/HelpPage.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    IconDetail: typeof import('./components/IconDetail.vue')['default']
    Icons: typeof import('./components/Icons.vue')['default']
    IconSet: typeof import('./components/IconSet.vue')['default']
    InstallIconSet: typeof import('./components/InstallIconSet.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalDialog: typeof import('./components/ModalDialog.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavElectron: typeof import('./components/electron/NavElectron.vue')['default']
    NavPlaceholder: typeof import('./components/electron/NavPlaceholder.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SearchElectron: typeof import('./components/electron/SearchElectron.vue')['default']
    SettingsCollectionsList: typeof import('./components/SettingsCollectionsList.vue')['default']
    SnippetPreview: typeof import('./components/SnippetPreview.vue')['default']
    WithNavbar: typeof import('./components/WithNavbar.vue')['default']
  }
}
